easy_admin:
   entities:
       # List the entity class name you want to manage
      #  - App\Entity\Product
      #  - App\Entity\Category
      User:
            class: App\Entity\User
            label: label.user
            new:
                title:  field.user.add_new
                fields:

                    # plain password 
                    - { property: plainPassword, label: User_password, type: 'password' }
      Events:
        class: App\Entity\Events 
      Patient:
        class: App\Entity\Patient 
      

       